version: "3.8"

services:
  moodle:
    build:
      context: ./_apache_docker
    container_name: moodle-apache
    ports:
      - "8080:80" # Expose Moodle on localhost:8080
    environment:
      - MOODLE_URL=http://localhost:8080
      - MOODLE_DB_TYPE=pgsql # mariadb|pgsql|mssql
      - MOODLE_DB_HOST=db_postgres # db_mariadb|db_pgsql|db_mssql
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=moodlepassword
    volumes:
      - .:/var/www/html
      - /d/Work/202504_VAA/2025_Moodle/moodledata:/var/www/moodledata
      # - /d/Work/202504_VAA/2025_Moodle/2025-lms-quocbaoit-dev:/var/www/html # Mount source code vào container
    depends_on:
      - db_postgres

  # moodle:
  #   image: moodlehq/moodleapp:latest
  #   container_name: moodle
  #   ports:
  #     - "8080:80" # Expose Moodle on localhost:8080
  #   environment:
  #     - MOODLE_URL=http://localhost:8080
  #     - MOODLE_DB_TYPE=pgsql # mariadb|pgsql|mssql
  #     - MOODLE_DB_HOST=db_postgres # db_mariadb|db_pgsql|db_mssql
  #     - MOODLE_DB_NAME=moodle
  #     - MOODLE_DB_USER=moodleuser
  #     - MOODLE_DB_PASSWORD=moodlepassword
  #   volumes:
  #     - .:/var/www/html/moodle
  #     - /d/Work/202504_VAA/2025_Moodle/moodledata:/var/www/moodledata
  #     # - /d/Work/202504_VAA/2025_Moodle/2025-lms-quocbaoit-dev:/var/www/html # Mount source code vào container
  #   depends_on:
  #     - db_postgres

  # db_mariadb:
  #   image: mariadb:10.5
  #   container_name: moodle-db-mariadb
  #   environment:
  #     - MYSQL_DATABASE=moodle
  #     - MYSQL_USER=moodleuser
  #     - MYSQL_PASSWORD=moodlepassword
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #   volumes:
  #     - dbdata:/var/lib/mysql

  db_postgres:
    image: postgres:17.4
    container_name: moodle-db-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_DB=moodle
      # - POSTGRES_USER=moodleuser
      # - POSTGRES_PASSWORD=moodlepassword
      - POSTGRES_PASSWORD=1234
    volumes:
      - dbdata:/var/lib/postgresql/data

  # db_mssql:
  #   # image: mcr.microsoft.com/mssql/server:2019-latest
  #   image: mcr.microsoft.com/azure-sql-edge
  #   container_name: moodle-db-mssql
  #   environment:
  #     - ACCEPT_EULA=Y
  #     # - MSSQL_PID=Express # for 2019
  #     - MSSQL_DATABASE=moodle
  #     - MSSQL_USER=moodleuser
  #     - MSSQL_PASSWORD=moodlepassword
  #     - SA_PASSWORD=StrongRootPassword123!
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - dbdata:/var/opt/mssql

volumes:
  moodledata:
  dbdata:
