version: "3.8"

services:
  moodle:
    build:
      context: ./_docker_apache
    container_name: moodle-apache
    # ports:
    #   # - "8080:80" # Expose Moodle on localhost:8080
    expose:
      - 80
    environment:
      MOODLE_URL: http://127.0.0.1:80
      MOODLE_DB_TYPE: pgsql # mariadb|pgsql|mssql
      MOODLE_DB_HOST: db_postgres # db_mariadb|db_pgsql|db_mssql
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: moodlepassword
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
      # - /d/Work/202504_VAA/2025_Moodle/2025-lms-quocbaoit-dev:/var/www/html # Mount source code vào container
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:17.4
    container_name: moodle-db-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_DB=moodle
      # - POSTGRES_USER=moodleuser
      # - POSTGRES_PASSWORD=moodlepassword
      # - POSTGRES_PASSWORD=1234
      POSTGRES_DB: ${POSTGRES_DB_MOODLE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

    # db_mssql:
    #   # image: mcr.microsoft.com/mssql/server:2019-latest
    #   image: mcr.microsoft.com/azure-sql-edge
    #   container_name: moodle-db-mssql
    #   environment:
    #     - ACCEPT_EULA=Y
    #     # - MSSQL_PID=Express # for 2019
    #     - MSSQL_DATABASE=moodle
    #     - MSSQL_USER=moodleuser
    #     - MSSQL_PASSWORD=moodlepassword
    #     - SA_PASSWORD=StrongRootPassword123!
    #   ports:
    #     - "1433:1433"
    #   volumes:
    #     - dbdata:/var/opt/mssql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 to the outside world
    volumes:
      - ./_docker_nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - moodle
      # - backend

volumes:
  moodledata:
  dbdata:
